name: Publish images

on: [workflow_dispatch]

jobs:
  push_to_registry:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ['8.0', '7.4']

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2.3.4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1.4.0
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.5.0
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          build-args: |
            "VERSION_PREFIX=${{ matrix.php }}-"
          cache-from: type=registry,ref=rechtlogisch/ffier:${{ matrix.php }}
          cache-to: type=inline
          tags: rechtlogisch/ffier:${{ matrix.php }}
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
